# 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
log_level: 1

grpc_server:
  address: "127.0.0.1:53001"  # required
  log_level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  log_verbosity: 9

metrics_server:
  enabled: true
  address: "127.0.0.1:53002" # required when enabled is true
  url_path: "/metrics"

zeppelin_flink_home: "/Users/gxlevi/bigdata/flink-1.12.2"
zeppelin_flink_execute_jars: "MySQL:/Users/gxlevi/bigdata/lib/flink-connector-jdbc_2.11-1.12.2.jar;Kafka:/Users/gxlevi/bigdata/lib/flink-sql-connector-kafka_2.11-1.12.3.jar"

sourcemanager_server:
  address: "127.0.0.1:50001"
  log_level: 2
  log_verbosity: 99

udfmanager_server:
  address: "127.0.0.1:52001"
  log_level: 2
  log_verbosity: 99

filemanager_server:
  address: "127.0.0.1:56001"
  log_level: 2
  log_verbosity: 99

tracer:
  service_name: "jobdeveloper"
  local_agent: "127.0.0.1:6831"
