# 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
log_level: 1

grpc_server:
  address: "127.0.0.1:9109"  # required
  log_level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  log_verbosity: 9

metrics_server:
  enabled: true
  address: "127.0.0.1:9209" # required when enabled is true
  url_path: "/metrics"

#zeppelin_flink_home: "/home/lzzhang/bigdata/flink-bin-download/flink-1.11.2"
#zeppelin_flink_execute_jars: "MySQL:/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/flink-connector-jdbc_2.11-1.11.2.jar,/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/mysql-connector-java-8.0.21.jar;PostgreSQL:/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/flink-connector-jdbc_2.11-1.11.2.jar,/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/postgresql-42.2.18.jar;Kafka:/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/flink-sql-connector-kafka_2.11-1.11.2.jar;ClickHouse:/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/flink-connector-clickhouse-1.11.0.jar"
zeppelin_flink_home: "/home/lzzhang/bigdata/flink_bin/flink-1.12.3"
zeppelin_flink_execute_jars: "MySQL:/home/lzzhang/bigdata/flinkjarlib/1.12_lib/flink-connector-jdbc_2.11-1.12.3.jar,/home/lzzhang/bigdata/flinkjarlib/1.12_lib/mysql-connector-java-8.0.21.jar;PostgreSQL:/home/lzzhang/bigdata/flinkjarlib/1.12_lib/flink-connector-jdbc_2.11-1.12.3.jar,/home/lzzhang/bigdata/flinkjarlib/1.12_lib/postgresql-42.2.18.jar;Kafka:/home/lzzhang/bigdata/flinkjarlib/1.12_lib/flink-sql-connector-kafka_2.11-1.12.3.jar;ClickHouse:/home/lzzhang/bigdata/flinkjarlib/1.12_lib/flink-connector-clickhouse-1.0-SNAPSHOT.jar,/home/lzzhang/bigdata/flinkjarlib/1.12_lib/guava-19.0.jar"

zeppelin_hadoop_conf: "/opt/homebrew/Cellar/hadoop/3.3.1/libexec/etc/hadoop"

sourcemanager_server:
  address: "127.0.0.1:9104"
  log_level: 2
  log_verbosity: 99

udfmanager_server:
  address: "127.0.0.1:9106"
  log_level: 2
  log_verbosity: 99

filemanager_server:
  address: "127.0.0.1:9111"
  log_level: 2
  log_verbosity: 99

enginemanager_server:
  address: "127.0.0.1:9114"
  log_level: 2
  log_verbosity: 99

tracer:
  service_name: "jobdeveloper"
  local_agent: "127.0.0.1:6831"
